"""Adding enquedita and nano moura

Revision ID: 16d098f8f5b5
Revises: 620269978fce
Create Date: 2022-03-26 18:31:01.796851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d098f8f5b5'
down_revision = '620269978fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquedita_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1999), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message')
    )
    op.create_table('nano_moura_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1999), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nano_moura_messages')
    op.drop_table('enquedita_messages')
    # ### end Alembic commands ###
