"""empty message

Revision ID: 18448c2a372b
Revises: 16d098f8f5b5
Create Date: 2022-05-08 22:42:53.544077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18448c2a372b'
down_revision = '16d098f8f5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colorful_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('selection', sa.String(length=1999), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1999), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colorful_selection')
    # ### end Alembic commands ###
