"""empty message

Revision ID: 620269978fce
Revises: 
Create Date: 2022-03-11 17:26:15.792517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620269978fce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tongo_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1999), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tongo_messages')
    # ### end Alembic commands ###
